Map<String, Map<String, dynamic>?> countryData = {
  'AF': {
    'country': 'Afghanistan',
    'internalPhoneCode': '93',
    'countryCode': 'AF',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'AL': {
    'country': 'Albania',
    'internalPhoneCode': '355',
    'countryCode': 'AL',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'DZ': {
    'country': 'Algeria',
    'internalPhoneCode': '213',
    'countryCode': 'DZ',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'AS': {
    'country': 'American Samoa',
    'internalPhoneCode': '1684',
    'countryCode': 'AS',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'AD': {
    'country': 'Andorra',
    'internalPhoneCode': '376',
    'countryCode': 'AD',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'AO': {
    'country': 'Angola',
    'internalPhoneCode': '244',
    'countryCode': 'AO',
    'prefix': '+000',
    'phoneMask': '0000 000 0000',
  },
  'AI': {
    'country': 'Anguilla',
    'internalPhoneCode': '1264',
    'countryCode': 'AI',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'AG': {
    'country': 'Antigua and Barbuda',
    'internalPhoneCode': '1268',
    'countryCode': 'AG',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'AR': {
    'country': 'Argentina',
    'internalPhoneCode': '54',
    'countryCode': 'AR',
    'prefix': '+00',
    'phoneMask': '0 000 0000',
  },
  'AM': {
    'country': 'Armenia',
    'internalPhoneCode': '374',
    'countryCode': 'AM',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'AW': {
    'country': 'Aruba',
    'internalPhoneCode': '297',
    'countryCode': 'AW',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'AU': {
    'country': 'Australia',
    'internalPhoneCode': '61',
    'countryCode': 'AU',
    'prefix': '+00',
    'phoneMask': '0000 0000',
    'altMasks': [
      '0 0000 0000',
    ],
  },
  'AT': {
    'country': 'Austria',
    'internalPhoneCode': '43',
    'countryCode': 'AT',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'AZ': {
    'country': 'Azerbaijan',
    'internalPhoneCode': '994',
    'countryCode': 'AZ',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'BS': {
    'country': 'Bahamas',
    'internalPhoneCode': '1242',
    'countryCode': 'BS',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'BH': {
    'country': 'Bahrain',
    'internalPhoneCode': '973',
    'countryCode': 'BH',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'BD': {
    'country': 'Bangladesh',
    'internalPhoneCode': '880',
    'countryCode': 'BD',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'BB': {
    'country': 'Barbados',
    'internalPhoneCode': '1246',
    'countryCode': 'BB',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'BY': {
    'country': 'Belarus',
    'internalPhoneCode': '375',
    'countryCode': 'BY',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'BE': {
    'country': 'Belgium',
    'internalPhoneCode': '32',
    'countryCode': 'BE',
    'prefix': '+00',
    'phoneMask': '000 00 00 00',
  },
  'BZ': {
    'country': 'Belize',
    'internalPhoneCode': '501',
    'countryCode': 'BZ',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'BJ': {
    'country': 'Benin',
    'internalPhoneCode': '229',
    'countryCode': 'BJ',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'BM': {
    'country': 'Bermuda',
    'internalPhoneCode': '1441',
    'countryCode': 'BM',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'BT': {
    'country': 'Bhutan',
    'internalPhoneCode': '975',
    'countryCode': 'BT',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'BA': {
    'country': 'Bosnia and Herzegovina',
    'internalPhoneCode': '387',
    'countryCode': 'BA',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'BW': {
    'country': 'Botswana',
    'internalPhoneCode': '267',
    'countryCode': 'BW',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'BR': {
    'country': 'Brazil',
    'internalPhoneCode': '55',
    'countryCode': 'BR',
    'prefix': '+00',
    'phoneMask': '(00) 0000-0000',
    'altMasks': [
      '(00) 00000-0000',
    ],
  },
  'IO': {
    'country': 'British Indian Ocean Territory',
    'internalPhoneCode': '246',
    'countryCode': 'IO',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'BG': {
    'country': 'Bulgaria',
    'internalPhoneCode': '359',
    'countryCode': 'BG',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'BF': {
    'country': 'Burkina Faso',
    'internalPhoneCode': '226',
    'countryCode': 'BF',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'BI': {
    'country': 'Burundi',
    'internalPhoneCode': '257',
    'countryCode': 'BI',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'KH': {
    'country': 'Cambodia',
    'internalPhoneCode': '855',
    'countryCode': 'KH',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'CM': {
    'country': 'Cameroon',
    'internalPhoneCode': '237',
    'countryCode': 'CM',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'US': {
    'country': 'United States',
    'internalPhoneCode': '1',
    'countryCode': 'US',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'CA': {
    'country': 'Canada',
    'internalPhoneCode': '1',
    'countryCode': 'CA',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'CV': {
    'country': 'Cape Verde',
    'internalPhoneCode': '238',
    'countryCode': 'CV',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'KY': {
    'country': 'Cayman Islands',
    'internalPhoneCode': '345',
    'countryCode': 'KY',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'CF': {
    'country': 'Central African Republic',
    'internalPhoneCode': '236',
    'countryCode': 'CF',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'TD': {
    'country': 'Chad',
    'internalPhoneCode': '235',
    'countryCode': 'TD',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'CL': {
    'country': 'Chile',
    'internalPhoneCode': '56',
    'countryCode': 'CL',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'CN': {
    'country': 'China',
    'internalPhoneCode': '86',
    'countryCode': 'CN',
    'prefix': '+00',
    'phoneMask': '000 0000 0000',
  },
  'CX': {
    'country': 'Christmas Island',
    'internalPhoneCode': '61',
    'countryCode': 'CX',
    'prefix': '+00',
    'phoneMask': '0 0000 0000',
  },
  'CO': {
    'country': 'Colombia',
    'internalPhoneCode': '57',
    'countryCode': 'CO',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'KM': {
    'country': 'Comoros',
    'internalPhoneCode': '269',
    'countryCode': 'KM',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'CG': {
    'country': 'Congo',
    'internalPhoneCode': '242',
    'countryCode': 'CG',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'CK': {
    'country': 'Cook Islands',
    'internalPhoneCode': '682',
    'countryCode': 'CK',
    'prefix': '+682',
    'phoneMask': '00 000',
  },
  'CR': {
    'country': 'Costa Rica',
    'internalPhoneCode': '506',
    'countryCode': 'CR',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'HR': {
    'country': 'Croatia',
    'internalPhoneCode': '385',
    'countryCode': 'HR',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'CU': {
    'country': 'Cuba',
    'internalPhoneCode': '53',
    'countryCode': 'CU',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'CY': {
    'country': 'Cyprus',
    'internalPhoneCode': '357',
    'countryCode': 'CY',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'CZ': {
    'country': 'Czech Republic',
    'internalPhoneCode': '420',
    'countryCode': 'CZ',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'DK': {
    'country': 'Denmark',
    'internalPhoneCode': '45',
    'countryCode': 'DK',
    'prefix': '+00',
    'phoneMask': '0 000 0000',
  },
  'DJ': {
    'country': 'Djibouti',
    'internalPhoneCode': '253',
    'countryCode': 'DJ',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'DM': {
    'country': 'Dominica',
    'internalPhoneCode': '1767',
    'countryCode': 'DM',
    'prefix': '+0000',
    'phoneMask': '000 0000',
  },
  'DO': {
    'country': 'Dominican Republic',
    'internalPhoneCode': '1809',
    'countryCode': 'DO',
    'prefix': '+0000',
    'phoneMask': '000 0000',
  },
  'EC': {
    'country': 'Ecuador',
    'internalPhoneCode': '593',
    'countryCode': 'EC',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'EG': {
    'country': 'Egypt',
    'internalPhoneCode': '20',
    'countryCode': 'EG',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'SV': {
    'country': 'El Salvador',
    'internalPhoneCode': '503',
    'countryCode': 'SV',
    'prefix': '+000',
    'phoneMask': '00 0000 0000',
  },
  'GQ': {
    'country': 'Equatorial Guinea',
    'internalPhoneCode': '240',
    'countryCode': 'GQ',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'ER': {
    'country': 'Eritrea',
    'internalPhoneCode': '291',
    'countryCode': 'ER',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'EE': {
    'country': 'Estonia',
    'internalPhoneCode': '372',
    'countryCode': 'EE',
    'prefix': '+000',
    'phoneMask': '000 000',
    'altMasks': [
      '000 0000',
      '0000 0000',
      '000000000',
    ]
  },
  'ET': {
    'country': 'Ethiopia',
    'internalPhoneCode': '251',
    'countryCode': 'ET',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'FO': {
    'country': 'Faroe Islands',
    'internalPhoneCode': '298',
    'countryCode': 'FO',
    'prefix': '+000',
    'phoneMask': '000000',
  },
  'FJ': {
    'country': 'Fiji',
    'internalPhoneCode': '679',
    'countryCode': 'FJ',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'FI': {
    'country': 'Finland',
    'internalPhoneCode': '358',
    'countryCode': 'FI',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'FR': {
    'country': 'France',
    'internalPhoneCode': '33',
    'countryCode': 'FR',
    'prefix': '+00',
    'phoneMask': '0 00 00 00 00',
  },
  'GF': {
    'country': 'French Guiana',
    'internalPhoneCode': '594',
    'countryCode': 'GF',
    'prefix': '+000',
    'phoneMask': '000 00 00 00',
  },
  'PF': {
    'country': 'French Polynesia',
    'internalPhoneCode': '689',
    'countryCode': 'PF',
    'prefix': '+000',
    'phoneMask': '000000',
  },
  'GA': {
    'country': 'Gabon',
    'internalPhoneCode': '241',
    'countryCode': 'GA',
    'prefix': '+000',
    'phoneMask': '000000',
  },
  'GM': {
    'country': 'Gambia',
    'internalPhoneCode': '220',
    'countryCode': 'GM',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'GE': {
    'country': 'Georgia',
    'internalPhoneCode': '995',
    'countryCode': 'GE',
    'prefix': '+000',
    'phoneMask': '000 000000',
  },
  'DE': {
    'country': 'Germany',
    'internalPhoneCode': '49',
    'countryCode': 'DE',
    'prefix': '+00',
    'phoneMask': '00 000000000',
  },
  'GH': {
    'country': 'Ghana',
    'internalPhoneCode': '233',
    'countryCode': 'GH',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'GI': {
    'country': 'Gibraltar',
    'internalPhoneCode': '350',
    'countryCode': 'GI',
    'prefix': '+000',
    'phoneMask': '00000',
  },
  'GR': {
    'country': 'Greece',
    'internalPhoneCode': '30',
    'countryCode': 'GR',
    'prefix': '+00',
    'phoneMask': '0 000 0000',
  },
  'GL': {
    'country': 'Greenland',
    'internalPhoneCode': '299',
    'countryCode': 'GL',
    'prefix': '+000',
    'phoneMask': '000000',
  },
  'GD': {
    'country': 'Grenada',
    'internalPhoneCode': '1473',
    'countryCode': 'GD',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'GP': {
    'country': 'Guadeloupe',
    'internalPhoneCode': '590',
    'countryCode': 'GP',
    'prefix': '+000',
    'phoneMask': '000 00 00 00',
  },
  'GU': {
    'country': 'Guam',
    'internalPhoneCode': '1671',
    'countryCode': 'GU',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'GT': {
    'country': 'Guatemala',
    'internalPhoneCode': '502',
    'countryCode': 'GT',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'GN': {
    'country': 'Guinea',
    'internalPhoneCode': '224',
    'countryCode': 'GN',
    'prefix': '+000',
    'phoneMask': '000 000000',
  },
  'GW': {
    'country': 'Guinea-Bissau',
    'internalPhoneCode': '245',
    'countryCode': 'GW',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'GY': {
    'country': 'Guyana',
    'internalPhoneCode': '592',
    'countryCode': 'GY',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'HT': {
    'country': 'Haiti',
    'internalPhoneCode': '509',
    'countryCode': 'HT',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'HN': {
    'country': 'Honduras',
    'internalPhoneCode': '504',
    'countryCode': 'HN',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'HU': {
    'country': 'Hungary',
    'internalPhoneCode': '36',
    'countryCode': 'HU',
    'prefix': '+00',
    'phoneMask': '0 000 0000',
    'altMasks': [
      '00 000 0000',
    ],
  },
  'IS': {
    'country': 'Iceland',
    'internalPhoneCode': '354',
    'countryCode': 'IS',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'IN': {
    'country': 'India',
    'internalPhoneCode': '91',
    'countryCode': 'IN',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'ID': {
    'country': 'Indonesia',
    'internalPhoneCode': '62',
    'countryCode': 'ID',
    'prefix': '+00',
    'phoneMask': '00 0000 0000',
  },
  'IQ': {
    'country': 'Iraq',
    'internalPhoneCode': '964',
    'countryCode': 'IQ',
    'prefix': '+000',
    'phoneMask': '(00) 000 00000',
  },
  'IE': {
    'country': 'Ireland',
    'internalPhoneCode': '353',
    'countryCode': 'IE',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'IL': {
    'country': 'Israel',
    'internalPhoneCode': '972',
    'countryCode': 'IL',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'IT': {
    'country': 'Italy',
    'internalPhoneCode': '39',
    'countryCode': 'IT',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'JM': {
    'country': 'Jamaica',
    'internalPhoneCode': '1876',
    'countryCode': 'JM',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'JP': {
    'country': 'Japan',
    'internalPhoneCode': '81',
    'countryCode': 'JP',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'JO': {
    'country': 'Jordan',
    'internalPhoneCode': '962',
    'countryCode': 'JO',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  '77': {
    'KZ': 'Kazakhstan',
    'internalPhoneCode': '77',
    'phoneCode': '7',
    'countryCode': 'KZ',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'KE': {
    'country': 'Kenya',
    'internalPhoneCode': '254',
    'countryCode': 'KE',
    'prefix': '+000',
    'phoneMask': '000 000000',
  },
  'KI': {
    'country': 'Kiribati',
    'internalPhoneCode': '686',
    'countryCode': 'KI',
    'prefix': '+000',
    'phoneMask': '00000',
  },
  'KW': {
    'country': 'Kuwait',
    'internalPhoneCode': '965',
    'countryCode': 'KW',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'KG': {
    'country': 'Kyrgyzstan',
    'internalPhoneCode': '996',
    'countryCode': 'KG',
    'prefix': '+000',
    'phoneMask': '000 000000',
  },
  'LV': {
    'country': 'Latvia',
    'internalPhoneCode': '371',
    'countryCode': 'LV',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'LB': {
    'country': 'Lebanon',
    'internalPhoneCode': '961',
    'countryCode': 'LB',
    'prefix': '+000',
    'phoneMask': '00 000 000',
  },
  'LS': {
    'country': 'Lesotho',
    'internalPhoneCode': '266',
    'countryCode': 'LS',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'LR': {
    'country': 'Liberia',
    'internalPhoneCode': '231',
    'countryCode': 'LR',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'LI': {
    'country': 'Liechtenstein',
    'internalPhoneCode': '423',
    'countryCode': 'LI',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'LT': {
    'country': 'Lithuania',
    'internalPhoneCode': '370',
    'countryCode': 'LT',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'LU': {
    'country': 'Luxembourg',
    'internalPhoneCode': '352',
    'countryCode': 'LU',
    'prefix': '+000',
    'phoneMask': '000000',
  },
  'MG': {
    'country': 'Madagascar',
    'internalPhoneCode': '261',
    'countryCode': 'MG',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'MW': {
    'country': 'Malawi',
    'internalPhoneCode': '265',
    'countryCode': 'MW',
    'prefix': '+000',
    'phoneMask': '000000000',
  },
  'MY': {
    'country': 'Malaysia',
    'internalPhoneCode': '60',
    'countryCode': 'MY',
    'prefix': '+00',
    'phoneMask': '0 000 0000',
  },
  'MV': {
    'country': 'Maldives',
    'internalPhoneCode': '960',
    'countryCode': 'MV',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'ML': {
    'country': 'Mali',
    'internalPhoneCode': '223',
    'countryCode': 'ML',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'MT': {
    'country': 'Malta',
    'internalPhoneCode': '356',
    'countryCode': 'MT',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'MH': {
    'country': 'Marshall Islands',
    'internalPhoneCode': '692',
    'countryCode': 'MH',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'MQ': {
    'country': 'Martinique',
    'internalPhoneCode': '596',
    'countryCode': 'MQ',
    'prefix': '+000',
    'phoneMask': '000 00 00 00',
  },
  'MR': {
    'country': 'Mauritania',
    'internalPhoneCode': '222',
    'countryCode': 'MR',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'MU': {
    'country': 'Mauritius',
    'internalPhoneCode': '230',
    'countryCode': 'MU',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'YT': {
    'country': 'Mayotte',
    'internalPhoneCode': '262',
    'countryCode': 'YT',
    'prefix': '+000',
    'phoneMask': '000 00 00 00',
  },
  'MX': {
    'country': 'Mexico',
    'internalPhoneCode': '52',
    'countryCode': 'MX',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'MC': {
    'country': 'Monaco',
    'internalPhoneCode': '377',
    'countryCode': 'MC',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'MN': {
    'country': 'Mongolia',
    'internalPhoneCode': '976',
    'countryCode': 'MN',
    'prefix': '+000',
    'phoneMask': '00 000000',
  },
  'ME': {
    'country': 'Montenegro',
    'internalPhoneCode': '382',
    'countryCode': 'ME',
    'prefix': '+000',
    'phoneMask': '00 000000',
  },
  'MS': {
    'country': 'Montserrat',
    'internalPhoneCode': '1664',
    'countryCode': 'MS',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'MA': {
    'country': 'Morocco',
    'internalPhoneCode': '212',
    'countryCode': 'MA',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'MM': {
    'country': 'Myanmar',
    'internalPhoneCode': '95',
    'countryCode': 'MM',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'NA': {
    'country': 'Namibia',
    'internalPhoneCode': '264',
    'countryCode': 'NA',
    'prefix': '+000',
    'phoneMask': '00 000000',
  },
  'NR': {
    'country': 'Nauru',
    'internalPhoneCode': '674',
    'countryCode': 'NR',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'NP': {
    'country': 'Nepal',
    'internalPhoneCode': '977',
    'countryCode': 'NP',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'NL': {
    'country': 'Netherlands',
    'internalPhoneCode': '31',
    'countryCode': 'NL',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'AN': {
    'country': 'Netherlands Antilles',
    'internalPhoneCode': '599',
    'countryCode': 'AN',
    'prefix': '+000',
    'phoneMask': '00000000',
  },
  'NC': {
    'country': 'New Caledonia',
    'internalPhoneCode': '687',
    'countryCode': 'NC',
    'prefix': '+000',
    'phoneMask': '000000',
  },
  'NZ': {
    'country': 'New Zealand',
    'internalPhoneCode': '64',
    'countryCode': 'NZ',
    'prefix': '+00',
    'phoneMask': '(0) 000 0000',
    'altMasks': [
      '(00) 000 0000',
      '(000) 000 0000',
    ],
  },
  'NI': {
    'country': 'Nicaragua',
    'internalPhoneCode': '505',
    'countryCode': 'NI',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'NE': {
    'country': 'Niger',
    'internalPhoneCode': '227',
    'countryCode': 'NE',
    'prefix': '+000',
    'phoneMask': '00 000000',
  },
  'NG': {
    'country': 'Nigeria',
    'internalPhoneCode': '234',
    'countryCode': 'NG',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'NU': {
    'country': 'Niue',
    'internalPhoneCode': '683',
    'countryCode': 'NU',
    'prefix': '+000',
    'phoneMask': '0000000',
  },
  'NF': {
    'country': 'Norfolk Island',
    'internalPhoneCode': '672',
    'countryCode': 'NF',
    'prefix': '+000',
    'phoneMask': '0 00 000',
  },
  'MP': {
    'country': 'Northern Mariana Islands',
    'internalPhoneCode': '1670',
    'countryCode': 'MP',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'NO': {
    'country': 'Norway',
    'internalPhoneCode': '47',
    'countryCode': 'NO',
    'prefix': '+00',
    'phoneMask': '0000 0000',
  },
  'OM': {
    'country': 'Oman',
    'internalPhoneCode': '968',
    'countryCode': 'OM',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'PK': {
    'country': 'Pakistan',
    'internalPhoneCode': '92',
    'countryCode': 'PK',
    'prefix': '+00',
    'phoneMask': '0000000',
  },
  'PW': {
    'country': 'Palau',
    'internalPhoneCode': '680',
    'countryCode': 'PW',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'PA': {
    'country': 'Panama',
    'internalPhoneCode': '507',
    'countryCode': 'PA',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'PG': {
    'country': 'Papua New Guinea',
    'internalPhoneCode': '675',
    'countryCode': 'PG',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'PY': {
    'country': 'Paraguay',
    'internalPhoneCode': '595',
    'countryCode': 'PY',
    'prefix': '+000',
    'phoneMask': '000 000000',
  },
  'PE': {
    'country': 'Peru',
    'internalPhoneCode': '51',
    'countryCode': 'PE',
    'prefix': '+00',
    'phoneMask': '00 000000000',
  },
  'PH': {
    'country': 'Philippines',
    'internalPhoneCode': '63',
    'countryCode': 'PH',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'PL': {
    'country': 'Poland',
    'internalPhoneCode': '48',
    'countryCode': 'PL',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'PT': {
    'country': 'Portugal',
    'internalPhoneCode': '351',
    'countryCode': 'PT',
    'prefix': '+000',
    'phoneMask': '000 000 000',
  },
  'PR': {
    'country': 'Puerto Rico',
    'internalPhoneCode': '1939',
    'countryCode': 'PR',
    'prefix': '+0000',
    'phoneMask': '000 0000',
  },
  'QA': {
    'country': 'Qatar',
    'internalPhoneCode': '974',
    'countryCode': 'QA',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'RO': {
    'country': 'Romania',
    'internalPhoneCode': '40',
    'countryCode': 'RO',
    'prefix': '+00',
    'phoneMask': '000 000 000',
  },
  'RW': {
    'country': 'Rwanda',
    'internalPhoneCode': '250',
    'countryCode': 'RW',
    'prefix': ' 000',
    'phoneMask': '00 000',
  },
  'WS': {
    'country': 'Samoa',
    'internalPhoneCode': '685',
    'countryCode': 'WS',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'SM': {
    'country': 'San Marino',
    'internalPhoneCode': '378',
    'countryCode': 'SM',
    'prefix': '+000',
    'phoneMask': '0000 000000',
  },
  'SA': {
    'country': 'Saudi Arabia',
    'internalPhoneCode': '966',
    'countryCode': 'SA',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'SN': {
    'country': 'Senegal',
    'internalPhoneCode': '221',
    'countryCode': 'SN',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'RS': {
    'country': 'Serbia',
    'internalPhoneCode': '381',
    'countryCode': 'RS',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'SC': {
    'country': 'Seychelles',
    'internalPhoneCode': '248',
    'countryCode': 'SC',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'SL': {
    'country': 'Sierra Leone',
    'internalPhoneCode': '232',
    'countryCode': 'SL',
    'prefix': '+000',
    'phoneMask': '00 000000',
  },
  'SG': {
    'country': 'Singapore',
    'internalPhoneCode': '65',
    'countryCode': 'SG',
    'prefix': '+00',
    'phoneMask': '0000 0000',
  },
  'SK': {
    'country': 'Slovakia',
    'internalPhoneCode': '421',
    'countryCode': 'SK',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'SI': {
    'country': 'Slovenia',
    'internalPhoneCode': '386',
    'countryCode': 'SI',
    'prefix': '+000',
    'phoneMask': '0 000 00 00',
  },
  'SB': {
    'country': 'Solomon Islands',
    'internalPhoneCode': '677',
    'countryCode': 'SB',
    'prefix': '+000',
    'phoneMask': '00000',
  },
  'ZA': {
    'country': 'South Africa',
    'internalPhoneCode': '27',
    'countryCode': 'ZA',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'GS': {
    'country': 'South Georgia and the South Sandwich Islands',
    'internalPhoneCode': '500',
    'countryCode': 'GS',
    'prefix': '+000',
    'phoneMask': '00000',
  },
  'ES': {
    'country': 'Spain',
    'internalPhoneCode': '34',
    'countryCode': 'ES',
    'prefix': '+00',
    'phoneMask': '000 000 000',
  },
  'LK': {
    'country': 'Sri Lanka',
    'internalPhoneCode': '94',
    'countryCode': 'LK',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'SD': {
    'country': 'Sudan',
    'internalPhoneCode': '249',
    'countryCode': 'SD',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'SR': {
    'country': 'Suriname',
    'internalPhoneCode': '597',
    'countryCode': 'SR',
    'prefix': '+000',
    'phoneMask': '000000',
  },
  'SZ': {
    'country': 'Swaziland',
    'internalPhoneCode': '268',
    'countryCode': 'SZ',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'SE': {
    'country': 'Sweden',
    'internalPhoneCode': '46',
    'countryCode': 'SE',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'CH': {
    'country': 'Switzerland',
    'internalPhoneCode': '41',
    'countryCode': 'CH',
    'prefix': '+00',
    'phoneMask': '00 000 0000',
  },
  'TJ': {
    'country': 'Tajikistan',
    'internalPhoneCode': '992',
    'countryCode': 'TJ',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'TH': {
    'country': 'Thailand',
    'internalPhoneCode': '66',
    'countryCode': 'TH',
    'prefix': '+00',
    'phoneMask': '0 000 0000',
  },
  'TG': {
    'country': 'Togo',
    'internalPhoneCode': '228',
    'countryCode': 'TG',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'TK': {
    'country': 'Tokelau',
    'internalPhoneCode': '690',
    'countryCode': 'TK',
    'prefix': '+000',
    'phoneMask': '0000',
  },
  'TO': {
    'country': 'Tonga',
    'internalPhoneCode': '676',
    'countryCode': 'TO',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'TT': {
    'country': 'Trinidad and Tobago',
    'internalPhoneCode': '1868',
    'countryCode': 'TT',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'TN': {
    'country': 'Tunisia',
    'internalPhoneCode': '216',
    'countryCode': 'TN',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'TR': {
    'country': 'Turkey',
    'internalPhoneCode': '90',
    'countryCode': 'TR',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'TM': {
    'country': 'Turkmenistan',
    'internalPhoneCode': '993',
    'countryCode': 'TM',
    'prefix': '+000',
    'phoneMask': '00 000000',
  },
  'TC': {
    'country': 'Turks and Caicos Islands',
    'internalPhoneCode': '1649',
    'countryCode': 'TC',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'TV': {
    'country': 'Tuvalu',
    'internalPhoneCode': '688',
    'countryCode': 'TV',
    'prefix': '+000',
    'phoneMask': '00000',
  },
  'UG': {
    'country': 'Uganda',
    'internalPhoneCode': '256',
    'countryCode': 'UG',
    'prefix': '+000',
    'phoneMask': '000 000000',
  },
  'UA': {
    'country': 'Ukraine',
    'internalPhoneCode': '380',
    'countryCode': 'UA',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'AE': {
    'country': 'United Arab Emirates',
    'internalPhoneCode': '971',
    'countryCode': 'AE',
    'prefix': '+000',
    'phoneMask': '00 000000',
    'altMasks': [
      '00 0000000',
    ],
  },
  'GB': {
    'country': 'United Kingdom',
    'internalPhoneCode': '44',
    'countryCode': 'GB',
    'prefix': '+00',
    'phoneMask': '0000 000000',
  },
  'UY': {
    'country': 'Uruguay',
    'internalPhoneCode': '598',
    'countryCode': 'UY',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'UZ': {
    'country': 'Uzbekistan',
    'internalPhoneCode': '998',
    'countryCode': 'UZ',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'VU': {
    'country': 'Vanuatu',
    'internalPhoneCode': '678',
    'countryCode': 'VU',
    'prefix': '+000',
    'phoneMask': '00000',
  },
  'WF': {
    'country': 'Wallis and Futuna',
    'internalPhoneCode': '681',
    'countryCode': 'WF',
    'prefix': '+‎',
    'phoneMask': '00 00 0000',
  },
  'YE': {
    'country': 'Yemen',
    'internalPhoneCode': '967',
    'countryCode': 'YE',
    'prefix': '+000',
    'phoneMask': '0 000000',
  },
  'ZM': {
    'country': 'Zambia',
    'internalPhoneCode': '260',
    'countryCode': 'ZM',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'ZW': {
    'country': 'Zimbabwe',
    'internalPhoneCode': '263',
    'countryCode': 'ZW',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'AX': {
    'country': 'Land Islands',
    'internalPhoneCode': '354',
    'countryCode': 'AX',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'BO': {
    'country': 'Bolivia, Plurinational State of',
    'internalPhoneCode': '591',
    'countryCode': 'BO',
    'prefix': '+000',
    'phoneMask': '000 000 0000',
  },
  'BN': {
    'country': 'Brunei Darussalam',
    'internalPhoneCode': '673',
    'countryCode': 'BN',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'CC': {
    'country': 'Cocos (Keeling) Islands',
    'internalPhoneCode': '61',
    'countryCode': 'CC',
    'prefix': '+00',
    'phoneMask': '0 0000 0000',
  },
  'CD': {
    'country': 'Congo, The Democratic Republic of the',
    'internalPhoneCode': '243',
    'countryCode': 'CD',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'CI': {
    'country': 'Cote d\'Ivoire',
    'internalPhoneCode': '225',
    'countryCode': 'CI',
    'prefix': '+000',
    'phoneMask': '00000000',
  },
  'FK': {
    'country': 'Falkland Islands (Malvinas)',
    'internalPhoneCode': '500',
    'countryCode': 'FK',
    'prefix': '+000',
    'phoneMask': '00000',
  },
  'GG': {
    'country': 'Guernsey',
    'internalPhoneCode': '44',
    'countryCode': 'GG',
    'prefix': '+00',
    'phoneMask': '(0) 0000 000000',
  },
  'HK': {
    'country': 'Hong Kong',
    'internalPhoneCode': '852',
    'countryCode': 'HK',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'IR': {
    'country': 'Iran, Islamic Republic of',
    'internalPhoneCode': '98',
    'countryCode': 'IR',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'KP': {
    'country': 'Korea, Democratic People\'s Republic of',
    'internalPhoneCode': '850',
    'countryCode': 'KP',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'KR': {
    'country': 'Korea, Republic of',
    'internalPhoneCode': '82',
    'countryCode': 'KR',
    'prefix': '+00',
    'phoneMask': '0 000 0000',
  },
  'LA': {
    'country': '(Laos) Lao People\'s Democratic Republic',
    'internalPhoneCode': '856',
    'countryCode': 'LA',
    'prefix': '+000',
    'phoneMask': '00 0000 0000',
  },
  'LY': {
    'country': 'Libyan Arab Jamahiriya',
    'internalPhoneCode': '218',
    'countryCode': 'LY',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'MO': {
    'country': 'Macao',
    'internalPhoneCode': '853',
    'countryCode': 'MO',
    'prefix': '+000',
    'phoneMask': '0000 0000',
  },
  'MK': {
    'country': 'Macedonia',
    'internalPhoneCode': '389',
    'countryCode': 'MK',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'FM': {
    'country': 'Micronesia, Federated States of',
    'internalPhoneCode': '691',
    'countryCode': 'FM',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'MD': {
    'country': 'Moldova, Republic of',
    'internalPhoneCode': '373',
    'countryCode': 'MD',
    'prefix': '+000',
    'phoneMask': '000 00000',
  },
  'MZ': {
    'country': 'Mozambique',
    'internalPhoneCode': '258',
    'countryCode': 'MZ',
    'prefix': '+000',
    'phoneMask': '000 000000',
  },
  'PS': {
    'country': 'Palestina',
    'internalPhoneCode': '970',
    'countryCode': 'PS',
    'prefix': '+000',
    'phoneMask': '0 000 0000',
  },
  'PN': {
    'country': 'Pitcairn',
    'internalPhoneCode': '64',
    'countryCode': 'PN',
    'prefix': '+00',
    'phoneMask': '0 000 0000',
  },
  'RE': {
    'country': 'Réunion',
    'internalPhoneCode': '262',
    'countryCode': 'RE',
    'prefix': '+000',
    'phoneMask': '000 00 00 00',
  },
  'RU': {
    'country': 'Russia',
    'internalPhoneCode': '7',
    'countryCode': 'RU',
    'prefix': '+0',
    'phoneMask': '(000) 000-00-00',
  },
  'BL': {
    'country': 'Saint Barthélemy',
    'internalPhoneCode': '590',
    'countryCode': 'BL',
    'prefix': '+000',
    'phoneMask': '000 00 00 00',
  },
  'SH': {
    'country': 'Saint Helena, Ascension and Tristan Da Cunha',
    'internalPhoneCode': '290',
    'countryCode': 'SH',
    'prefix': '+000',
    'phoneMask': '0000',
  },
  'KN': {
    'country': 'Saint Kitts and Nevis',
    'internalPhoneCode': '1869',
    'countryCode': 'KN',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'LC': {
    'country': 'Saint Lucia',
    'internalPhoneCode': '1758',
    'countryCode': 'LC',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'MF': {
    'country': 'Saint Martin',
    'internalPhoneCode': '590',
    'countryCode': 'MF',
    'prefix': '+000',
    'phoneMask': '000 000000',
  },
  'PM': {
    'country': 'Saint Pierre and Miquelon',
    'internalPhoneCode': '508',
    'countryCode': 'PM',
    'prefix': '+508',
    'phoneMask': '00 00 00',
  },
  'VC': {
    'country': 'Saint Vincent and the Grenadines',
    'internalPhoneCode': '1784',
    'countryCode': 'VC',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'ST': {
    'country': 'Sao Tome and Principe',
    'internalPhoneCode': '239',
    'countryCode': 'ST',
    'prefix': '+000',
    'phoneMask': '000 0000',
  },
  'SO': {
    'country': 'Somalia',
    'internalPhoneCode': '252',
    'countryCode': 'SO',
    'prefix': '+000',
    'phoneMask': '00 000 000',
  },
  'SJ': {
    'country': 'Svalbard and Jan Mayen',
    'internalPhoneCode': '47',
    'countryCode': 'SJ',
    'prefix': '+00',
    'phoneMask': '0000 0000',
  },
  'SY': {
    'country': 'Syrian Arab Republic',
    'internalPhoneCode': '963',
    'countryCode': 'SY',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'TW': {
    'country': 'Taiwan',
    'internalPhoneCode': '886',
    'countryCode': 'TW',
    'prefix': '+000',
    'phoneMask': '0 0000 0000',
  },
  'TZ': {
    'country': 'Tanzania',
    'internalPhoneCode': '255',
    'countryCode': 'TZ',
    'prefix': '+000',
    'phoneMask': '00 000 0000',
  },
  'TL': {
    'country': 'Timor-Leste',
    'internalPhoneCode': '670',
    'countryCode': 'TL',
    'prefix': '+000',
    'phoneMask': '000 000',
  },
  'VE': {
    'country': 'Venezuela, Bolivarian Republic of',
    'internalPhoneCode': '58',
    'countryCode': 'VE',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'VN': {
    'country': 'Viet Nam',
    'internalPhoneCode': '84',
    'countryCode': 'VN',
    'prefix': '+00',
    'phoneMask': '000 000 0000',
  },
  'VG': {
    'country': 'Virgin Islands, British',
    'internalPhoneCode': '1284',
    'countryCode': 'VG',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  },
  'VI': {
    'country': 'Virgin Islands, U.S.',
    'internalPhoneCode': '1340',
    'countryCode': 'VI',
    'prefix': '+0',
    'phoneMask': '(000) 000 0000',
  }
};
